Milestone 3 : Add desktop version
jaflih/Portfolio pull request #4
Opened 2021-11-30 11:33 UTC by jihaneH

Milestone 3: Add desktop version

2021-11-30 19:58 UTC, MrBrN197 requested changes
## Hi, @jihaneH 👋 

You've done a really nice job so far.
There are some issues that you still need to work on to go to the next project but you are almost there!
## To highlight 👏👏
- ✔ Your design is really great 👍. It matches the Figma really well.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 19:58 UTC, MrBrN197 commented on index.html
> +            </form>
- [ ] Your design is really good 👏👏. I noticed that your button is not aligned to the right. on the Desktop if you notice that is the case. Please make this change to keep in line with the Figma 👍.
## Figma Design
![image](https://user-images.githubusercontent.com/18730106/144118525-2e74004d-eade-4836-b8e9-df109b15678c.png)

## Your Design 
![image](https://user-images.githubusercontent.com/18730106/144118405-58199dca-df2b-4bb9-9029-b4380b5b7da5.png)

- [ ] Notice also that the `textarea` on the Figma template has a green border. Please also make this change 🙏.

2021-11-30 20:20 UTC, jaflih commented on index.html
> +            </form>
Thank you for the feedback. I thought that it was green only when the mouse over it. I change it, and I change also the button place.

2021-11-30 20:30 UTC, MrBrN197 approved these changes
## Hi, @jihaneH  👏

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 20:47 UTC, merged

2022-01-28 21:07 UTC, jihaneH commented
@MrBrN197
![icegif-1433](https://user-images.githubusercontent.com/7243132/151621519-730b3cf7-e619-47a0-8938-df755bc7f29a.gif)